version: '3'

services:
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:  
      - node-network

  app:
    build:
      context: ./node
    container_name: app  
    image: alairc/fullcycle-node:latest
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db 

  nginx:
    restart: always
    container_name: nginx_node
    tty: true
    image: alairc/fullcycle-node-nginx:latest
    build:
        context: ./nginx
    networks:
      - node-network
    ports:
        - "8080:80"
    depends_on:
      - app 

networks:
  node-network:
    driver: bridge
      